apiVersion: v1
kind: Service
metadata:
  name: capital-gains
  namespace: we-love-sap
spec:
  type: ClusterIP 
  ports:
  - protocol: TCP
    port: 8080  
    targetPort: 8080  
  selector:
    app: capital-gains 
