apiVersion: v1
kind: Service
metadata:
  name: stocks
  namespace: we-love-sap
spec:
  type: ClusterIP  
  ports:
  - protocol: TCP
    port: 8000  
    targetPort: 8000  
  selector:
    app: stocks  
