apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
  namespace: we-love-sap  
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db