apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
  namespace: we-love-sap  
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi