apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: we-love-sap
spec:
  type: ClusterIP  
  ports:
  - protocol: TCP
    port: 27017  
    targetPort: 27017  
  selector:
    app: mongo  
